CREATE TABLE User (
	id INT AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(200),
	email VARCHAR(200),
	fb_id VARCHAR(40) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE Scores (
    id INT AUTO_INCREMENT PRIMARY KEY,
    score INT,
    achieved TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    userId INT NOT NULL,
    FOREIGN KEY (userId) REFERENCES User(id)
) ENGINE=InnoDB;


